name = "Underworld SMP"
author = "_notSalt"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "044c7e7e812da7d49671f0e9ad3f76b1ee5f88b60fe596c3353112dd05828414"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
