name = "Underworld SMP"
author = "_notSalt"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c679458c5d301d4c7d9ef3457d48bb5450df92c1d89fca0ec3d2084fda8c4471"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
