name = "Underworld SMP"
author = "_notSalt"
version = "1.4.0"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b8f6d9dac7e5f32ce07b83553f5019ac00dd5f2f7938de16c2a517f27b520bb"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
