name = "Underworld SMP"
author = "_notSalt"
version = "1.2.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72105229337dbe621db80b09acf87eb052d449570b245a8ff5abe44300719d62"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
