name = "Underworld SMP"
author = "_notSalt"
version = "1.2.1"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de397093741c4eeed974eb7388d43798ec4fd09f2123560cde3fca7c28ce00f0"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
