name = "Underworld SMP"
author = "_notSalt"
version = "1.1.1"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdbda433d3185bb665fd4bbbe651d9e9b25170e70dcc1c3e0513688d84f075f7"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
