name = "Underworld SMP"
author = "_notSalt"
version = "1.4.3"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c69919be340ae30cc0600736616ef8688700f2aa23c1e2e1411cd8ac41df34e2"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
