name = "Underworld SMP"
author = "_notSalt"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c377684a877adbc8f5956cab55b7d95683ce58fef36f90bcf6b4e6522bfa3e5"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
