name = "Underworld SMP"
author = "_notSalt"
version = "1.2.8"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b65c687cf04854e027cef3868dbd3ac55354d2a674e39fa77769eb0c786f0e2a"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
