name = "Underworld SMP"
author = "_notSalt"
version = "1.1.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc0e14b21e07620852c4997c605f0c6d43acc720c664534e05dbea5ee13c3304"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
