name = "Underworld SMP"
author = "_notSalt"
version = "1.4.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dcea1308bf211b18018f593ed8e017e89c05419a377766325eaa63f55eb193c"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
