name = "Underworld SMP"
author = "_notSalt"
version = "1.2.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd158bb5036adfdce9294d818441f8adbf63e937ef24632830508ed63d9d018c"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
