name = "Underworld SMP"
author = "_notSalt"
version = "1.2.0"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a41d0a34cb168185557903ef8827557daeca472f947b38e305c9403f27c2256"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
