name = "Underworld SMP"
author = "_notSalt"
version = "1.2.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72fdf7bc003e59b02333404d211e1aebf426b98db12c213214988e1967575ff5"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
