name = "Underworld SMP"
author = "_notSalt"
version = "1.5.0"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67bd098198c77c1e26b383edfa7af2e5cd56c9a5a25e1b03bdb36ac118010964"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
