name = "Underworld SMP"
author = "_notSalt"
version = "1.4.3"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47bd9f86fed806244e410d0aa2dfe799db8be8931695274f5a2afb87d60a0a96"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
