name = "Underworld SMP"
author = "_notSalt"
version = "1.2.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70bef7bf8696114d622df128c98ad74ded16fbfc9973ceb9f7d56f8ec7a4bf7b"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
