name = "Underworld SMP"
author = "_notSalt"
version = "1.3.0"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "659c5566b99f72bda4051393fc1ff028703d158b4b7dc1c955980cbabb15b639"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
