name = "Underworld SMP"
author = "_notSalt"
version = "1.2.9"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7415d6c9208145f22ae53ec5a333728bc6258bca2415a5149a58e9d344863f2"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
