name = "Underworld SMP"
author = "_notSalt"
version = "1.2.6"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fea2ff6f306f6fe85a744e9df72656049d6facb3f5e727958711ecf5a700b5c"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
