name = "Underworld SMP"
author = "_notSalt"
version = "1.4.1"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4503a5ef6521ba7ad729d16b6a574a11feedb3a242677ebc948508f319cfc0f6"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
