name = "Underworld SMP"
author = "_notSalt"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca694ec5a3643ead39047d4b2a0dee08b7ea164ce75a9448acab9f44605bc5d4"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
