name = "Underworld SMP"
author = "_notSalt"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb912a32adb05d033913aca4ce8617b965b3c9907701f73dbca7f0ce22d4fb2"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
