name = "Underworld SMP"
author = "_notSalt"
version = "1.1.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85c7ce9801a9a2020a7817d820427b134c3727aa3ff255f2638616d724161ddb"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
