name = "Underworld SMP"
author = "_notSalt"
version = "1.3.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d6077807db827fdb3e3a631e453291b6c3da87e24180cad60b7000aee3ad01"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
